### PR TITLE
remove facebook and twitter meta tags for images

### PR DESCRIPTION
**Pull request by KaitCrawford**
removed the meta tags specifiying the image to pull in an attempt to get facebook and twitter to automatically identify the images

### CODE REVIEW

**Comment by KaitCrawford** [comment]
@bruskiza @smn @miltontony

**Comment by bruskiza** [comment]
Problem is they want the image... @KaitCrawford

**Comment by KaitCrawford** [comment]
This is to test if they will identify the image automatically. Their docs say that they should. I believe the problem is in the image url we are sending through. @smn and I are looking at getting the url to the image now

**Comment by KaitCrawford** [comment]
@bruskiza @smn the above change uses the absolute url for the image rather than the relative url

**Comment by smn** [comment]
:+1:

**Pull request merged**
