### PR TITLE
fixed top nav "jumping"

### PR DESCRIPTION
**Pull request by KaitCrawford**

### CODE REVIEW

**Comment by KaitCrawford** [comment]
@smn @bruskiza @miltontony @saeedmb8

**Comment by KaitCrawford** [comment]
There's still a point where the font changes width by +- 4 pixels if the page is not cached. I can't find a solution for this problem

**Comment by smn** [comment]
Isn't this alway going to be the case? A lot of CSS dimensions are defined using sizes that depend on the  size of the font face. So once a font is cached then it won't jump anymore since the font is loaded before the sizes relative to fonts as used.

**Comment by KaitCrawford** [comment]
@smn basically, yes. However, I've managed to mitigate a large chunk of the "on-the-fly" resizing and styling changes and I wanted it noted somewhere that I hadn't managed to remove this one. Largely so that if it becomes an issue down the road and someone else tries to tackle it this might provide them with some context or somewhere to start.

**Comment by smn** [comment]
:+1:

**Pull request merged**
