### PR TITLE
Revert "made default background colour match the banner"

### PR DESCRIPTION
**Pull request by KaitCrawford**
This reverts commit 08b228e1bca5ce974088b9d1ce16bc0ca4701132.

### CODE REVIEW

**Comment by bruskiza** [comment]
:+1:

**Comment by KaitCrawford** [comment]
@bruskiza Please +1
reverted the change of the background colour as it also changed the background for the content pages

**Comment by miltontony** [comment]
@KaitCrawford is there no other css you can change for this? perhaps adding a specific class to the item that you want to change the color for?

**Comment by KaitCrawford** [comment]
@miltontony I'm going to look into that. However, I don't rate it as high priority (since I believe the continued presence of the "flash" is due to caching) and I wanted to get this reverted as soon as possible.

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
