### PR TITLE
ensure only authenticated staff users can flag comments

### PR DESCRIPTION
**Pull request by KaitCrawford**
@bruskiza @miltontony @smn @saeedmb8

### CODE REVIEW

**Comment by bruskiza** [comment]
:+1:

**Comment by miltontony** [comment]
Just noticing this ticket - I'm commenting on the Jira now. 
This shouldn't be considered a bug, it's the way it's supposed to work.

**Comment by miltontony** [comment]
:-1:

**Comment by bruskiza** [comment]
sorry! :\

**Comment by KaitCrawford** [comment]
@miltontony should non-staff users be able to flag comments? if not then there is still a bug here

**Comment by miltontony** [comment]
Yes, flagging via the frontend is actually targeted at normal users. Admin users are expected to flag comments via the CMS.

**Comment by miltontony** [comment]
It's also uncommon for staff users to comment (except during testing). Since Django doesn't log you out after you've logged in to the CMS, what we've found is that during testing, sometimes people don't log off (or use private browsing) so they end up making comments using the admin user account. In production however, the admin user would rarely comment, and when they do, they are usually adding comments to help the normal users, and so you wouldn't want their comments to be Flagged by normal users.

**Pull request closed without merging**
